# Generated by Django 4.0.4 on 2022-05-08 18:51

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Candidate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField()),
                ('cpf', models.CharField(max_length=11, unique=True)),
                ('birthdate', models.DateField()),
                ('address', models.TextField()),
                ('votes_on_plea', models.BigIntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Voter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cpf', models.CharField(max_length=11, unique=True)),
                ('password', models.CharField(max_length=30)),
                ('token', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Plea',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.TextField()),
                ('startDate', models.DateField()),
                ('endDate', models.DateField()),
                ('kind', models.TextField()),
                ('state', models.BooleanField(default=False)),
                ('voted_by', models.ManyToManyField(to='master.voter')),
            ],
        ),
    ]
