# Generated by Django 4.0.4 on 2022-05-08 19:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('master', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='candidate',
            name='current_plea',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='master.plea'),
            preserve_default=False,
        ),
    ]
