# Generated by Django 4.0.4 on 2022-05-09 19:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('master', '0002_candidate_current_plea'),
    ]

    operations = [
        migrations.AlterField(
            model_name='voter',
            name='cpf',
            field=models.CharField(max_length=14, unique=True),
        ),
    ]
