# Generated by Django 4.0.4 on 2022-05-09 19:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('master', '0003_alter_voter_cpf'),
    ]

    operations = [
        migrations.AlterField(
            model_name='candidate',
            name='cpf',
            field=models.CharField(max_length=14, unique=True),
        ),
    ]
